import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.80
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleFullscreen" },
  { key = "N", mods = "Command|Shift", action = "CreateNewWindow" },
  { key = "ArrowLeft", mods = "Command", action = "SelectPreviousTab" },
  { key = "ArrowRight", mods = "Command", action = "SelectNextTab" },
]

